%YAML:1.0
# There are the params which will be loaded by explore node.
# cloud_name: /cur_kp_cloud # rostopic type : sensor_msgs::PointCloud
# obs_count: 10
# obs_cost: 0.6
shooting_dst: 2.0 # 0.15 # length of  detection area
cam_width: 1.0 # 0.06 # width of  detection area
cam_height:  0.5 # 0.005 # height of  detection area
resolution: 0.05 # 0.005 # resolution of  detection area
kdtree_radius: 0.5 # scan radius of each point in detection area
kdtree_K: 0 # 0 - scan kdtree by distance , n - scan kdtree by particular points number.
cost_scaling_factor: 8.0 # factor multiply by cost calculated.
trapezoid_hei: 0.0
trapezoid_len: 0.0
dst_filter_factor: 0.1

